# Generated by Django 5.2.16 on 2026-07-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="alive",
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
